### ISSUE TITLE
Страница "Главная"

### ISSUE THREAD

**Issue by causer** [causer/tmk#1]
Макет: https://onedrive.live.com/?id=66338F737A630587%2159923&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3%2D2Zk&o=OneUp

**Comment by Weddin** [comment]
Завершена верстка главной страницы

**Comment by aonuchin** [comment]
Верстка:
1) Боковое меню
   б) Нет иконок рядом с пунктами меню
   в) Выравнивание пунктов должно быть по правому краю с отступом
3) Вертикальные скроллы не должны заходить на секцию с именами разделов
4) Нет вертикального скролла у раздела Консультации
5) Рекомендации - урезать количество отображаемого текста до 200 символов
8) Неверные шрифты

Functionality tasks removed correlate to incomplete #13

**Comment by aonuchin** [comment]
Актуальные проблемы:
3) Специализация должна быть полужирным
4) Часть надписей должна быть не черным, а серым (рекомендации - специализация врача, дата и время в чате и у консультаций, рекомендаций)

**Comment by aonuchin** [comment]
Недоработано:

1) Время и дата сообщения в блоке чата - слишком жирно, не сходится с макетом и забирает на себя фокус от основного текста
2) Рекомендации и консультации - должны быть только даты, без времени
3) Рекомендации - "Подробнее" должно быть подчеркнутым
4) Пропали иконки участников чата

**Comment by causer** [comment]
2) Блок чата сначала с заглушкой как на макете, при этом консультация ни одна не выделена
(comment moved from #13)
