### ISSUE TITLE
Страница "Врачи"

### ISSUE THREAD

**Issue by causer** [causer/tmk#11]

**Comment by aonuchin** [comment]
Актуальные ошибки:
1) Панель с фильтрами должна быть серой
2) Фильтр по ФИО пациента не содержит серой подсказки
3) Лупа у поля поиска по ФИО не с макета
4) Данные в выпадающем списке специализаций врачей - так оставлять нельзя
5) ФИО врача не должно быть жирным
6) нет иконки i после ФИО врача, по которой будет вызываться попап с деталями о враче
7) Иконки типов джоступных каналов связи не должны быть кликабельными - это только индикаторы. И сделать хотя бы одну серой
8) Обводка оранжевой кнопки почему-то зеленоватая
9) Не сделан вертикальный скролл
10) Всего записей. Количесво писать после двоеточия, а не тире
11) Контрол пейджинга не по макетам
12) Контрол количества записей на странице - стрелка вниз заехала полностью на текст

**Comment by GalinaMaslova** [comment]
Замечания по верстке. 
![default](https://cloud.githubusercontent.com/assets/13379131/8745728/bcfa6140-2c93-11e5-908c-4cf987451b39.png)

**Comment by Weddin** [comment]
pager делается кодом. классы для активной страницы и для неактивных кнопок тоже прописываются в коде
