### ISSUE TITLE
В поле "Отображать за период" неверно отображаются записи при выборе диапазона.

### ISSUE THREAD

**Issue by GalinaMaslova** [causer/tmk#148]
1) Авторизуемся в системе как Доктор.
2) Переходим на страницу "Моя запись" или "Баланс".
3) В поле "Отображать за период" выбираем фильтр "Указать диапазон". 
4) Конечную дату выбираем ранее начальной. 
Результат:
начальная дата становится равной конечной. В таблице не отображаются записи.
Ожидаемый результат:
начальная дата становится равной конечной. В таблице отображаются записи за указанную дату.

**Comment by kirill-yatsy** [comment]
В поле "Отображать за период" неверно отображаются записи при выборе фильтра "Сегодня" #147
