### ISSUE TITLE
В профиле Пациента не отображаются рекомендации на странице "Моя история"

### ISSUE THREAD

**Issue by GalinaMaslova** [causer/tmk#151]
Сценарий:
1) Авторизуемся в системе как Пациент.
2) Переходим на страницу "Моя история".
Результат:
в блоке " Рекомендации" не отображаются рекомендации от врача.
Ожидаемый результат: 
в блоке "Рекомендации" отображаются рекомендации Пациента от врача.

**Comment by kirill-yatsy** [comment]
- фикс фильтров рекомендаций в чате
