### ISSUE TITLE
Верстка главной страницы Доктора

### ISSUE THREAD

**Issue by causer** [causer/tmk#2]
Макет: https://onedrive.live.com/?id=66338F737A630587%2159806&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3%2D2Zk&o=OneUp

**Comment by causer** [comment]
Переоткрываю, вижу сверстано не по метрике. Если метрики нет-  запросить у Наташи.

**Comment by Weddin** [comment]
https://smwdrq-sn3302.files.1drv.com/y3mpdimX31jGUNgokVititqoCU1nwrbsfx68NbLbP7GR4Dnl7RY0e48EbzUaHnUpccUmZnPR9UMmuxNdiTe_Z21ffkPuY0fM8hq7eFI3sXmsTPh4R9xUDgpoJpQt_lCXGXRvk3hsN2bKZszazrpgxQ4LOCJX51skcbkd1FL5W7EZAhjkABU-FXZiGiyF4Ji6CMB/Spec_1.png?psid=1

**Comment by causer** [comment]
[19/07/15 20:18:26] Vyacheslav Borisov: Недочеты.
1. Шрифт отображающий выбранный диапазон дат не жирный.
2. Кнопки влево-вправо имеют стрелки не с макета.
3. Кнопка выбранного месяца  имеет неправильный шрифт, должно быть все прописными буквами.
4. Кнопка + Добавить имеет неправильный цвет.
5. Записанные пациенты => Записи на сегодня.
6. Таблица “Записи на сегодня” имеет другой набор колонок нежели на макете.
[19/07/15 20:18:28] Vyacheslav Borisov: что еще?
[19/07/15 20:21:31] Галина Маслова: 7. Кнопка "Месяц" должна по умолчанию отображать слово Месяц.
8. Шапка календаря должна отображаться в виде: вс 19

**Comment by causer** [comment]
Макет: https://onedrive.live.com/?id=66338F737A630587%2160259&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3%2D2Zk&o=OneUp

**Comment by Weddin** [comment]
Кнопка месяц по умолчанию показывает Месяц, но контрол при инициализации устанавливает текущий месяц
