### ISSUE TITLE
Верстка модального окна при завершении чата

### ISSUE THREAD

**Issue by causer** [causer/tmk#85]

**Comment by Weddin** [comment]
Пациент https://onedrive.live.com/?id=66338F737A630587%2160463&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3-2Zk&o=OneUp

**Comment by Weddin** [comment]
Врач https://onedrive.live.com/?id=66338F737A630587%2160462&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3-2Zk&o=OneUp
