### ISSUE TITLE
Страница "Баланс и оплата"

### ISSUE THREAD

**Issue by causer** [causer/tmk#9]
Верстка страницы пациента "Баланс и оплата" по макету:
https://onedrive.live.com/?id=66338F737A630587%2160023&cid=66338F737A630587&group=0&parId=66338F737A630587%2159803&authkey=%21ADjibr7McZ3%2D2Zk&o=OneUp

**Comment by GalinaMaslova** [comment]
Замечания по верстке. 
![default](https://cloud.githubusercontent.com/assets/13379131/8744805/30ee0f9c-2c8b-11e5-8abf-5c46b4a1de16.png)
